apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icinga-kubernetes.configmapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yml: |-
    {{- include "icinga-kubernetes.config" . | nindent 4 }}
