name: Release Charts

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - charts/**/Chart.yaml

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser icinga-stack
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts
          skip_existing: true

      - name: Run chart-releaser icinga2
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts/icinga-stack/charts/icinga2
          skip_existing: true

      - name: Run chart-releaser icingadb
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts/icinga-stack/charts/icingadb
          skip_existing: true

      - name: Run chart-releaser icinga-kubernetes
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts/icinga-stack/charts/icinga-kubernetes
          skip_existing: true

      - name: Run chart-releaser icingaweb2
        continue-on-error: true
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./charts/icinga-stack/charts/icingaweb2
          skip_existing: true

